### PR TITLE
Added a command line flag for passing different configuration file

### LINKED ISSUE #6: The name of the config file is hard coded
We are not using the `-config` flag for opening config files with any given name

### PR DESCRIPTION
**Pull request by hellozee**
Fixes #6

### CODE REVIEW

**Comment by farhaanbukhsh** [comment]
What is the ussability should we mention on how to use this in `Readme.md`?

**Comment by hellozee** [comment]
Onto you, I am pretty bad at writing docs

**Comment by farhaanbukhsh** [comment]
Can you make me understand what are we trying to do here?

**Comment by hellozee** [comment]
As you can see [here](https://github.com/ILUGD/splatter/blob/master/main.go) to pass the configuration file to the program, I am using the `-config` flag that way the name for the configuration file is not hardcoded also to make sure the code doesn't break, I have made it optional so that if someone hasn't passed anything to the program, the program will take `config.json` in the current directory as default.

**Comment by farhaanbukhsh** [comment]
We need to figure out how can we do this with `fresh` as well for now fresh runs main.go without any way to pass a config to it.

**Comment by hellozee** [comment]
We don't need to, thinking of the same, I set `config.json` the default file name for the configuration file

**Pull request closed without merging**
