### PR TITLE
Added a MakeFile for the ease of development

### LINKED ISSUE #5: Create a MakeFile for ease of setting up

### PR DESCRIPTION
**Pull request by hellozee**
Fixes #5

### CODE REVIEW

**Comment by farhaanbukhsh** [comment]
Instead of go run main.go, should we have fresh-c fresh.conf?

**Comment by hellozee** [comment]
Actually I have never used fresh, would be nice if you can share some pointers

**Comment by hellozee** [comment]
Okay, tried using fresh, but if you run program from outside of the logs directory, the program crashes with a segfault

**Comment by farhaanbukhsh** [comment]
Also can we put some dummy data too?

Like let's have a `make dev` which puts dummy data, `make build` sets up the repo for normal ussage and `make clean` which cleans all the data

what say?

**Comment by hellozee** [comment]
Love the idea but dummy data as in?

**Comment by farhaanbukhsh** [comment]
Like some dummy logfiles, also can you update the Readme too?

**Comment by hellozee** [comment]
sure I would also update the readme

**Comment by hellozee** [comment]
Will prepare a separate patch for the Readme update, till then please review the python script, I wrote for generating random data.

**Comment by hellozee** [comment]
Patch for the readme update #9

**Comment by farhaanbukhsh** [comment]
This looks fine the only thing bothering is the dummy data generated wouldn't be something which is useful

**Comment by farhaanbukhsh** [comment]
https://github.com/joke2k/faker

this can be used to do that

**Comment by farhaanbukhsh** [comment]
This could be a improvement over the mentioned PR https://github.com/farhaanbukhsh/file-indexer/issues/11

But this is amazing work and thanks a lot @hellozee

**Pull request merged**
