### PR TITLE
Create Dockerfile with multi-stage build as a builder pattern

### PR DESCRIPTION
**Pull request by Azaradel**
Fixes: #3 
I created Dockerfile for your file indexer, also added `docker-build` and `docker-run` steps to the Makefile for easy use of the docker image.
I used multi-staged Dockerfile because it solves the problem to use the builder pattern and in my honest opinion it is better than few dockerfiles and scripts for them in repository.

Ps. Present Dockerfile copies the default config.json and assumes that you have seeded project with example data.

### CODE REVIEW

**Comment by hellozee** [comment]
@Azaradel Thanks for the patch, I am not a container guy but it looks good to me.
cc @farhaanbukhsh

**Comment by hellozee** [comment]
This works fine when the files to indexed are also saved inside the same docker container but what about if they are saved in the local file system or another docker container?

**Comment by farhaanbukhsh** [comment]
We can always mount a local volume in the container

**Comment by hellozee** [comment]
Ohh nice, @farhaanbukhsh @Azaradel  what about passing a different config file while starting the container, since the program already supports different config file with the `-config` flag?

**Comment by farhaanbukhsh** [comment]
@Azaradel  this looks really cool.

@hellozee  we can always have a config build into the image if we need or we can modify the command in the container.

Either ways that can be done on a different PR.

**Comment by farhaanbukhsh** [comment]
Merging this in thanks @Azaradel

**Pull request merged**
