### PR TITLE
Add fresh in the makefile

### PR DESCRIPTION
**Pull request by farhaanbukhsh**
This is to understand that fresh is the external package that needs to be
installed and used with the service.

Signed-off-by: Farhaan Bukhsh <farhaan.bukhsh@gmail.com>

### CODE REVIEW

**Comment by farhaanbukhsh** [comment]
fixes https://github.com/farhaanbukhsh/file-indexer/issues/11

**Comment by hellozee** [comment]
LGTM, should we add that we need `python3` for the development purposes?

**Comment by farhaanbukhsh** [comment]
@hellozee added the change

**Comment by hellozee** [comment]
Cool I think we can merge it now

**Pull request merged**
